# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1ac5f5657ca9dd911981a61abe0e8a5187999cc2e6e1e5d19f8c1557f4e28005e0bc8db1bb7f7030784b089116411de538c33cc4063b91da38907ed7d1d9e86d

test:
  secret_key_base: b32d5de0a5b4b042b3217387169c572ddfb186b084e5abe821a5e6cf5744947a691a4a237c8c5b35d7766df14ee92c4ac9d8500904592ceee69621008918cf65

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
